=== saurabhsaindhane/XML-and-XML-Schema-of-Airplane-Database/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="class">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Airplane" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:string"/>
              <xs:element name="Make" type="xs:string"/>
              <xs:element name="Model" type="xs:string"/>
              <xs:element name="Seats" type="xs:positiveInteger"/>
              <xs:element name="EngineType" type="xs:string"/>
              <xs:element name="YearManufactured" type="xs:gYear"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== saurabhsaindhane/XML-and-XML-Schema-of-Airplane-Database/Airplane.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schema.xsd">
  <Airplane country = "India">
    <Id>A001</Id>
    <Make>Boeing</Make>
    <Model>747</Model>
    <Seats>400</Seats>
    <EngineType>Turbofan</EngineType>
    <YearManufactured>1998</YearManufactured>
  </Airplane>
  <Airplane country = "India">
    <Id>A002</Id>
    <Make>Airbus</Make>
    <Model>A380</Model>
    <Seats>853</Seats>
    <EngineType>Turbofan</EngineType>
    <YearManufactured>2007</YearManufactured>
  </Airplane>
  <Airplane country = "India">
    <Id>A003</Id>
    <Make>Embraer</Make>
    <Model>E190</Model>
    <Seats>114</Seats>
    <EngineType>Turbofan</EngineType>
    <YearManufactured>2004</YearManufactured>
  </Airplane>
</class>
